// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMagazin.Data;

#nullable disable

namespace WebApiMagazin.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20241014222403_MajCreditCard")]
    partial class MajCreditCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebApiMagazin.Model.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("WebApiMagazin.Model.CreditCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cvv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("expiration_month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("expiration_year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("WebApiMagazin.Model.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("id_client")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("id_credit_card")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_product")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("id_transaction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("shipping_price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("total_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApiMagazin.Model.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("In_stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("WebApiMagazin.Model.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("amount_charged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("success")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
